linters:
  enable-all: true
  disable:
    - gofumpt
    - godot
    - gci
    - funlen
    - golint
    - scopelint
    - wrapcheck
    - varnamelen
    - paralleltest
    - gomnd
    - thelper
    - nlreturn
    - exhaustivestruct
    - wsl
linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0
    skip-tests: true
